### ISSUE TITLE
XAPI backup issue with pool.

### ISSUE THREAD

**Issue by mkaliyannan** [izderadicka/xapi-back#5] opened 2016-01-07 10:52 UTC
Hi,

Do you got a chance to fix the issue on Xenserver pool. As you mentioned i got an eror 302 when the slave backups.

**Comment by izderadicka** [comment] 2016-01-07 11:02
Hi,

I'll look at it.  Such issue is expected because I have not tested on 
pool, just standalone XenServer.   The problem is that master sends back 
redirect response,  which is now not properly handled. I believe fix 
should be fairly easy.

Would you be able to test it once fix is provided?

Regards
I.

**Comment by kmohan1985** [comment] 2016-01-07 11:10
sure. I can test it for you. or If you want an access my lab let me know i will share my homelab.

**Comment by kmohan1985** [comment] 2016-01-07 11:19
Thanks for your valuable time. I will let you know once I done the test. 

Thanks,

Regards,
Mohan.

**Comment by kmohan1985** [comment] 2016-01-07 11:35
I found one more issue on restore. I wasn't able to restore by defined storage repository. The default one works well.. However, I can't define the SR. 

Said connection reset by peer

**Comment by izderadicka** [comment] 2016-01-07 13:39
If I remember correctly now xb can restore only to default storage 
repository - I'll need to refresh bit my Xen knowledge to see what 
exactly is going on.  It will be next good idea for improvement.
I.

**Comment by kmohan1985** [comment] 2016-01-07 16:57
Yes. your are correct. As you mentioned  it's restoring into default storage. It works!!! you are awesome. I think no one have a developed solutions like you as easier. 

Also lookup  XDelta3 backup so it will just backup only block changes from the last snapshot.

**Comment by izderadicka** [comment] 2016-01-07 20:15
xdelta3 sounds interesting however this will require much more changes 
into the tool.  For now it has fairly simple history of backups -   
keeps  last  x backups.  If there is already x backups last is deleted.  
However for incremental backups we have to add some additional logic -   
if deleting the oldest backup, second oldest backup must have been 
expanded first to full backup - which might take some time.   I guess 
this scheme could be more  useful if there will be more sophisticated 
backup scheme -   like when monthly and daily backup are done (monthly 
is full backup, daily is incremental). However this is now beyond scope 
of xb which should be fairly simple tool to small non-critical VMs.

I.

**Comment by izderadicka** [comment] 2016-01-07 20:25
Could you now please test pool branch from github -   it contains support for redirect so theoretically it should work in pool.
I.

**Comment by kmohan1985** [comment] 2016-01-07 22:58
I tried to rebuild. I got an error as below:

python setup.py install 

Cannot find version of package

**Comment by izderadicka** [comment] 2016-01-08 09:44
Fixed it (did not realize that version must follow certain format - 
x.y.z   for setuptools).   Can you pls try now.

I.

**Comment by kmohan1985** [comment] 2016-01-08 22:56
Works Perfect !!! The problem got fixed and also I notied the VM restore works well. It's restore's VM on preserved storage.

Good Job!!

**Comment by kmohan1985** [comment] 2016-01-09 01:09
There is a problem to restore the VM. If we don't have shared(NFS) storage it restore as it original state. If we have a shared storage it's restore to shared storage (NFS) as a template.

Is it possible to fix !!

**Comment by kmohan1985** [comment] 2016-01-09 01:10
I am interested to write to GUI with php.

**Comment by izderadicka** [comment] 2016-01-09 06:47
Could you please little bit more elaborate the problem?
What exactly you are trying to achieve?
What is your setup -  Xenserver version, pool setup etc.?

What about manual restore (via xa)  does it work differently?

I.

**Comment by izderadicka** [comment] 2016-01-09 07:02
It would be also better to open new issue for it.

I.

**Comment by mkaliyannan** [comment] 2016-01-09 07:35
My  current setup is 2 xenserver .

Version 6.5 patches with SP1 upto date.
Storage : 2 local storage ( named as local1 for server 1 followed by local 2 for server2)  + 1 NFS storage repository ( defaul storage)

Scenario : 

Server 1 is have running a  VM name called  CentOS-VM. ( VM disk is stored on local1 storage)
Server 2 is have running a VM name called Ubuntu-VM.     ( VM disk is stored on local2 storage)

If  I run a backup through your tool, it backup successfully either manual or automatic.

Restore : 

(1)  for instance If  I restore a CentOS-VM using  xb restore, it was restored to NFS storage and shown as template . Actually, It suppose to be restore on local1 storage and should be restore as VM. Not as a template.

(2)  If I removed the NFS storage from the pool then If  I take a backup and restore using your tool restore same as original state.

So need to be fix to restore to an original storage repository and should be avoid to store on NFS shared storage.

If the backups are stored in nfs, it will take long time to copy to original server so this must be avoided. 


![screenshot_1](https://cloud.githubusercontent.com/assets/8954012/12214993/4712bbb4-b666-11e5-9055-63ab470605b3.png)


The above mentioned arrow mark is pointing that backup is storing as a template.

**Comment by mkaliyannan** [comment] 2016-01-09 07:44
As you requested, I opened on another ticket.

**Comment by mkaliyannan** [comment] 2016-01-09 07:47
I haven't tested using xe command. I will let you know soon 

Sent from my iPhone

> On Jan 8, 2016, at 11:47 PM, Ivan Zderadicka <notifications@github.com> wrote:
> 
> Could you please little bit more elaborate the problem?
> What exactly you are trying to achieve?
> What is your setup - Xenserver version, pool setup etc.?
> 
> What about manual restore (via xa) does it work differently?
> 
> I.
> 
> On 9.1.2016 02:09, kmohan1985 wrote:
> >
> > There is a problem to restore the VM. If we don't have shared(NFS) 
> > storage it restore as it original state. If we have a shared storage 
> > it's restore to shared storage (NFS) as a template.
> >
> > Is it possible to fix !!
> >
> > —
> > Reply to this email directly or view it on GitHub 
> > <https://github.com/izderadicka/xapi-back/issues/5#issuecomment-170174358>.
> >
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Disclaimer in plain tex

**Comment by izderadicka** [comment] 2016-01-10 07:27
So can we close this one?

**Comment by mkaliyannan** [comment] 2016-01-11 22:51
Yes we can close this one.

**Closed** 2016-01-11 22:51 UTC
